### ISSUE TITLE
Show which users have been rated on the Leaderboard

### ISSUE THREAD

**Issue by navneel99** [devclub-iitd/ReviewSystem#24]
When the number of people get more, then it will be difficult to make note of who has been rated, and who hasn't. Some indicator must be present in the Leaderboard itself.

**Comment by navneel99** [comment]
The leaderboard in itself is pretty dry. Add more relevant information in the table.

**Comment by navneel99** [comment]
Added a column which shows whether the user has rated the other or not. Will create the pull request once the Registration Enabled one gets merged.

**Comment by DivyanshuSaxena** [comment]
Please check #37. Another solution for the same problem has been proposed.
