### ISSUE TITLE
No response on rating other

### ISSUE THREAD

**Issue by navneel99** [devclub-iitd/ReviewSystem#56]
There is no feedback from the page that one user has successfully rated other.

**Comment by DivyanshuSaxena** [comment]
Problem was in get and post functions.
Resolved in branch refactor-views in commit abbebad56875da4683a35e58c187ae4426be374a.

**Comment by DivyanshuSaxena** [comment]
Encryption of ratings is still not correct

**Comment by DivyanshuSaxena** [comment]
@navneel99  could you close this issue by citing the commit that cleared up the encryption issue?

**Comment by navneel99** [comment]
Ratings got encrypted twice.
Resolved the bug in f04da6c36381f8f6fba9ccf330edcdfa3222fe23
